name: CI

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        uses: psf/black@stable
        with:
          options: "--line-length 120 --check"
          src: "."
